### ISSUE TITLE
Code Not Up-to-Date

### ISSUE THREAD

**Issue by lawrencefoley** [worldreboot/twitch-reloaded-roku#11]
The code in this repo seems to be outdated when compared to the actual Roku app. (For example, the chat isn't in the code anywhere.)

I'd like to contribute to the project, but can't because it's not up to date.

**Comment by worldreboot** [comment]
If you have an idea that you want to implement with code, DM one of the developers on Discord with your idea and we will give you access to the newer repo. (Sorry for late response)

**Comment by lawrencefoley** [comment]
@worldreboot Is there a particular reason it can't be public? You'd be able to get more help from the community if it was.

**Comment by worldreboot** [comment]
@lawrencefoley The repo is now up-to-date
