### ISSUE TITLE
PLEASE REMOVE REGION LOCK

### ISSUE THREAD

**Issue by mrfhenix** [worldreboot/twitch-reloaded-roku#13]
is there something I could do to enable it outside USA?

**Comment by worldreboot** [comment]
Which country are you in? You can try using a VPN, as that has worked for some people. Roku does not allow private channels to be installed in Brazil or Mexico right now.

**Comment by mrfhenix** [comment]
well I would have to create a new USA Roku account and that's not an easy task

**Comment by worldreboot** [comment]
You can try manually installing the app if Twoku is not available in your region through the access code
