### ISSUE TITLE
Twoku crash started today

### ISSUE THREAD

**Issue by severd8** [worldreboot/twitch-reloaded-roku#22]
Twoku started crashing for me today. I've removed the app, reinstalled, and even tried the beta version. Same issue.

TCL 32-inch 3-Series 720p Roku Smart TV - 32S335, 2021 Model
Software version: 10.0.0 - Build 4195-48

**Comment by Neurism** [comment]
I am getting same issue :(

Same thing happened when Twitched got removed

**Comment by worldreboot** [comment]
Issue should be fixed

**Comment by severd8** [comment]
Working good! Thanks
