### ISSUE TITLE
403 when trying to add the channel

### ISSUE THREAD

**Issue by sharedito** [worldreboot/twitch-reloaded-roku#4]
I tried to add the channel to my Roku account, following the instructions in the README of this project. But I get a message saying:
```El código de canal brindado está asociado con un canal no disponible en tu región.```
```The channel code provided is associated to a channel not available in your region```

Could you please make the channel available in all regions? Or at least this one? I cannot find the region in my device or account, but I'm trying to add the channel from Mexico.

Thanks

**Comment by andrescane** [comment]
I'm from Argentina and get the same message.

**Comment by worldreboot** [comment]
I enabled the app for all the available stores (including Argentina). I don't know why its unavailable in your regions sorry

**Comment by worldreboot** [comment]
Apparently using a VPN to create an account works for people.

**Comment by worldreboot** [comment]
@sharedito @andrescane Can you guys try adding the channel again and see if it works now?

**Comment by andrescane** [comment]
It works now! Thank you!

**Comment by DerianAndre** [comment]
doesn't work for Mexico

**Comment by worldreboot** [comment]
Roku does not allow private channels to be installed in Mexico or Brazil
