### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Cedius3** [worldreboot/twitch-reloaded-roku#47]
Streams open then app force closes. Such a ds app

**Comment by jaredthecoder** [comment]
I see the same behavior.

**Comment by jaredthecoder** [comment]
I made a PR here - https://github.com/worldreboot/twitch-reloaded-roku/pull/48.

**Comment by jaredthecoder** [comment]
This is fixed now and left a detailed explanation on my PR #48. You can close this @Cedius3.
