### ISSUE TITLE
Features says Chat is available but can't use it?

### ISSUE THREAD

**Issue by MarellaB** [worldreboot/twitch-reloaded-roku#5]
This could be my own stupidity and if it is I apologize. But the features list says Chat is implemented yet I've found no way of actually viewing chat or interacting with it? This was even after digging around the code briefly to see if it was a button I was missing.

**Comment by worldreboot** [comment]
At the moment, chat (and other features) is not on the GitHub version. You can try using the access code version. Sorry, should have made it clearer.

**Comment by MarellaB** [comment]
I'm using the Access Code version and still can't find it. Is it a specific button to make the chat appear? Or a specific way to get to the stream that I'm not using? I've got some free time this weekend so wouldn't mind implementing it (potentially) if you'd like a PR for it?

**Comment by worldreboot** [comment]
You enable it in the options menu. Sorry, I don't feel like releasing the new code at the moment. Thanks for trying to help, though

**Comment by MarellaB** [comment]
Hey it's there and I can watch Twitch on my Roku I'm happy either way haha, thanks for making it and being so respondent!
