### ISSUE TITLE
Twoku crashes on launch, login code broken on re-add, heroku site down.

### ISSUE THREAD

**Issue by Kasey-py** [worldreboot/twitch-reloaded-roku#56]
I was trying to access Twoku just now via my Roku LE and it crashed before loading any streamers or stream previews.
I removed and re-added the app, and while this did fix the homepage, the code on the login screen appears to show the raw HTML rather than the actual code.
Additionally, when attempting to visit the Heroku authenticator page, I am met with this.
![image](https://github.com/user-attachments/assets/83e3b660-f6d8-4918-8989-2b49864a8d9e)

Please help.

**Comment by worldreboot** [comment]
Issue should be resolved. Let me know if there are any more issues.

**Comment by Kasey-py** [comment]
Website works now, but the app does not generate a code still.
