### ISSUE TITLE
Can't add channel on my Roky by access code (not available in my region)

### ISSUE THREAD

**Issue by rtrind** [worldreboot/twitch-reloaded-roku#6]
Hi,

I'm from Brazil and I'm not able to install your app by the access code. I tried installing the GitHub version using developer mode, but it does not work. The top menu is visible, nothing else is present on the screen and the buttons do nothing. 

Is there is any chance you would enable it to work for other regions to install the latest version using the access code?

Thanks!

**Comment by worldreboot** [comment]
I'm not sure if this works, but maybe you can try this: https://help.simpletelly.com/article/375-how-to-download-uk-or-us-restricted-tv-apps-for-roku

**Comment by rtrind** [comment]
These instructions need you to create a new account on another region, but I need some apps from my own region, so it's not a solution for me, unfortunately.

**Comment by ThiagoMusico** [comment]
@rtrind I'm from Brazil too.
I was able to install twoku via Manual Developer Install, but the channel doesn't work, as it was stated in the README.

**Comment by worldreboot** [comment]
The repo is now up-to-date and manually installing should now work if the app is not available in your region

**Comment by rtrind** [comment]
Thank you so much, working perfectly now!
