### ISSUE TITLE
help me with a project

### ISSUE THREAD

**Issue by xoceunder** [worldreboot/twitch-reloaded-roku#7]
I have a question, could you help me with a project?

**Comment by worldreboot** [comment]
What project?

**Comment by xoceunder** [comment]
I'm creating a project just like yours but I want to be able to make the movies change the audio and subtitle, choose and activate them

**Comment by xoceunder** [comment]
this email for send my file proyect @worldreboot

**Comment by worldreboot** [comment]
@xoceunder I think you should ask the Roku Slack server for help.

**Comment by xoceunder** [comment]
I want to do this in the movie area, do you think you can help me with this?

![18575A76-82F9-4523-A43A-F0306D3B259C](https://user-images.githubusercontent.com/12431116/92518474-69526100-f1e6-11ea-8030-cce0f18f1197.jpg)

**Comment by worldreboot** [comment]
@xoceunder message me on discord, not here
